### ISSUE TITLE
Trying to test locally and database table not created

### ISSUE THREAD

**Issue by afragen** [stuttter/wp-user-signups#1]
I'm trying to test locally and I get the following error.

> Table 'pressmatic.wp_signups' doesn't exist

**Comment by Mahjouba91** [comment]
Hello, did you setup a multisite installation ?

**Comment by afragen** [comment]
Yes this is on multisite.

**Comment by JJJ** [comment]
OIC.

It's hooked to `muplugins_loaded` which is too early for single-site, or if not in `mu-plugins`.

I'll see how it behaves when it's just network activated and report back.

**Comment by JJJ** [comment]
See: a1df3ea561fffbd25765e5ebf8bca0af162cd980
