### ISSUE TITLE
Bulk delete feature doesn't work

### ISSUE THREAD

**Issue by Mahjouba91** [stuttter/wp-user-signups#2]
Hello,

Thanks for your plugin that I use for weeks, it's very usefull.

I got one problem, in the signup list table, the bulk delete action don't work, nothing appears. I'm on a WordPress 4.7 installation and PHP 7.0

**Comment by JJJ** [comment]
Very sorry about this. It's plausible I forgot to implement it, or that I broke it somehow.

I'll look into this.

**Comment by JJJ** [comment]
Fixed in https://github.com/stuttter/wp-user-signups/commit/514091794eb107433e822722648fec0806456a66.
