### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by lkraav** [stuttter/wp-user-signups#4]
It's hard to tell what exactly this plugin does just by reading README.

**Comment by JJJ** [comment]
See: https://wordpress.org/plugins/wp-user-signups/

GitHub doesn't allow remote assets in README's, and I'd prefer not to bundle one with the plugin itself. Any ideas?

**Comment by lkraav** [comment]
Oh, indeed the plugin repo has them. Why the preference on not bundling? I was under the casual impression it was the preferred choice (have noticed a ton of `screenshot-1.jpg` type files in repos all around).

**Comment by JJJ** [comment]
I just made a Wiki here, as a place where some meta assets could possibly live.

Not opposed to bundling them if that's what folks want, but I usually choose not to because they aren't really necessary to be distributed across everyone's WordPress installations.
